swarup.bhol : swarup bhol 

server.port: 8080

spring:
## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medsoldb
    username: root
    password: password
## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:          
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect

# Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update

#Configuring eureka
eureka:
   client:
      service-url:
         default-zone: http://localhost:8761